name: Build project

on:
  push:
    branches:
      - develop

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  # TODO add versioning
  buildForPlatformsMatrix:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - .
        unityVersion:
          - 2019.3.12f1
        targetPlatform:
          - Android # Build an Android .apk standalone app.
          # - iOS # Build an iOS player.
          # - StandaloneWindows # Build a Windows standalone.
          # - StandaloneWindows64 # Build a Windows 64-bit standalone.
          # - StandaloneLinux64 # Build a Linux 64-bit standalone.
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: webbertakken/unity-builder@v0.11
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Custom  # TODO use "tag" versioning
          version: 0.0.3
      - uses: actions/upload-artifact@v1  # TODO replace with Firebase distribution
        with:
          name: Build
          path: build